version: "3"
networks:
  lms-network:
services:
  #######################book-service###########################
  book-app:
    container_name: book-app-container
    image: book-app
    restart: always
    build: ./BookServiceApp
    ports:
      - "9092:8080"
    environment:
      MYSQL_HOST: bookdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    networks:
      - lms-network
  #######################bookdb-service###########################
  bookdb:
    container_name: bookdb
    image: mysql:8.0.36
    volumes:
          - D:\Projects\college\react\SA\sw-project\bookV:/var/lib/mysql
    ports:
      - "4040:3306"
    environment:
      MYSQL_DATABASE: bookdb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - lms-network
  #######################user-service###########################
  user-app:
    container_name: user-app-container
    image: user-app
    restart: always
    build: ./UserServiceApp
    ports:
      - "9093:8080"
    environment:
      MYSQL_HOST: userdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    networks:
      - lms-network
  #######################userdb-service###########################
  userdb:
    container_name: userdb
    image: mysql:8.0.36
    volumes:
      - D:\Projects\college\react\SA\sw-project\userV:/var/lib/mysql
    ports:
      - "4041:3306"
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - lms-network
  #######################borrowing-service###########################
  borrowing-app:
    container_name: borrowing-app-container
    image: borrowing-app
    restart: always
    build: ./BorrowingServiceApp
    ports:
      - "9094:8080"
    environment:
      MYSQL_HOST: borrowingdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    networks:
      - lms-network
  #######################borrowingdb-service###########################
  borrowingdb:
    container_name: borrowingdb
    image: mysql:8.0.36
    volumes:
      - D:\Projects\college\react\SA\sw-project\borrowV:/var/lib/mysql
    ports:
      - "4042:3306"
    environment:
      MYSQL_DATABASE: borrowingdb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - lms-network
  #######################date and time -service###########################
  datetime-app:
    container_name: datetime-app-container
    image: datetime-app
    restart: always
    build: ./DateTimeServiceApp
    ports:
      - "9095:8080"
    networks:
      - lms-network
  #######################random numbers-service###########################
  randomnumber-app:
    container_name: randomnumber-container
    image: randomnumber-app
    restart: always
    build: ./RandomNumberServiceApp
    ports:
      - "9096:8080"
    networks:
      - lms-network
  #######################react-service###########################
  react:
    build: ./ReactServiceApp
    container_name: react-app-container
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - lms-network



